/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface OpenaiConversation {
  id: number;
  title: string;
  createdAt: string;
}

export interface OpenaiMessage {
  id: number;
  conversationId: number;
  role: string;
  content: string;
  createdAt: string;
}

export interface CreateOpenaiConversationBody {
  title: string;
}

export interface SendOpenaiMessageBody {
  content: string;
}

export interface OpenaiConversationWithMessages {
  id: number;
  title: string;
  createdAt: string;
  messages: OpenaiMessage[];
}

export interface OpenaiError {
  error: string;
}

export interface CheckCalendarConflictsBody {
  startTime: string;
  endTime: string;
}

export interface CalendarEventSummary {
  id: string;
  title: string;
  start: string;
  end: string;
}

export interface CalendarConflictsResult {
  hasConflicts: boolean;
  conflicts: CalendarEventSummary[];
}

export interface CreateCalendarEventBody {
  title: string;
  startTime: string;
  endTime: string;
  description?: string;
}

export interface CalendarEvent {
  id: string;
  title: string;
  start: string;
  end: string;
  description?: string;
  htmlLink?: string;
}
